### ISSUE TITLE
New widget - overflowing when a user is not logged in

### ISSUE THREAD

**Issue by DarrenBaldwin07** [dailydotdev/apps#1043]
> Very minor but thought I would throw an issue up for it.
# What is the issue?
## When accessing daily.dev and clicking on the new widget button in the upper right, it seems to overflow:

<img width="1718" alt="Screen Shot 2022-06-21 at 5 37 13 PM" src="https://user-images.githubusercontent.com/68653294/174902177-0853b898-c938-4e5f-87a7-9b61e4f08c0c.png">

> It works fine when a user is logged in
<img width="1662" alt="Screen Shot 2022-06-21 at 5 50 42 PM" src="https://user-images.githubusercontent.com/68653294/174903025-b69a9781-77a0-499d-99fc-979a18fa46e5.png">

# When does this issue occur?
- Only when no user is authenticated (this is likely due to the popup aligning with the "Access all features" button)
- When accessing the site via the web extension

# Steps to reproduce:
- Download the firefox, chrome, or edge extension
- open a new tab without being logged in

> Willing to create a PR for this if needed

**Comment by shubhimainalli** [comment]
I see this issue has been fixed. PFA 

![image](https://user-images.githubusercontent.com/70970530/185749110-abf49e87-acd8-48ff-b6e1-5d26245bde79.png)

**Comment by rebelchris** [comment]
@DarrenBaldwin07 This should have been fixed a while ago.
Please feel free to reopen a ticket [here](https://github.com/dailydotdev/daily/issues) if it still happens for you.
