### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by kramerlee** [dailydotdev/apps#1087]
Hello team,

I am currently unable to log in using my Github profile as well as my Google account. It says duplicate email address.

<img width="683" alt="image" src="https://user-images.githubusercontent.com/10692595/178242255-3dff4ba1-d0e0-4365-8e6a-f89e2e7610ab.png">

Please help with this. Thanks team very much!

**Comment by shubhimainalli** [comment]
Can you please try login in again, As I checked its working for me. PFA 
![Untitled design (6)](https://user-images.githubusercontent.com/70970530/185748994-a318ad52-74ea-4461-b1cd-60ec406572f0.png)

**Comment by rebelchris** [comment]
Hi @kramerlee we revamped our whole login system.
Can you please check if the new system is working for you.

Closing this so long.
You can always open a new ticket here: https://github.com/dailydotdev/daily/issues
