### ISSUE TITLE
[FIX] improve `Dockerfile`

### ISSUE THREAD

**Issue by Pradumnasaraf** [dailydotdev/apps#1328]
**Hey,**

### Chnages proposed

We can improve the image build time and size by reducing the number of layers in the `Dockerfile` by using wildcards. As both layers (pairs which I bordered out in the below image) are dependent on each other for changes, it is safe and good practice to bundle them together.

![Untitled design](https://user-images.githubusercontent.com/51878265/196510768-03263840-93df-4d33-816f-97fa77066e56.png)

### How to changes will look like

```diff
- COPY package.json .
- COPY package-lock.json .
+ COPY package*.json .
```

```diff
- COPY packages/eslint-config/package.json ./packages/eslint-config/
- COPY packages/eslint-config/package-lock.json ./packages/eslint-config/
+ COPY packages/eslint-config/package*.json ./packages/eslint-config/
```
(For all the 7 pairs which I bordered out in the below image)

### Impovement goal

-  To reduce the layers form 25 to 18 
-  Fast image build and reduced the size

**Comment by rebelchris** [comment]
@Pradumnasaraf Sounds like a good plan, if you are up for it feel free to take it on 🙏

**Comment by Pradumnasaraf** [comment]
Thank you, @rebelchris. I will soon raise a PR.
