### ISSUE TITLE
[Extension] Browser extension is not able to connect to API

### ISSUE THREAD

**Issue by dynamitechetan** [dailydotdev/apps#1341]
- I am able to run the webapp on localhost - 
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/14369357/198705954-9128071b-de3e-42e8-a64a-e48e40e88958.png">

<br>

- But while running the browser extension, i am getting this error and no post is loaded.
<img width="418" alt="image" src="https://user-images.githubusercontent.com/14369357/198705804-29a77dda-89dc-4408-bc69-1962be5936c9.png">

can you guys please suggest whats wrong with this.

**Comment by rebelchris** [comment]
Hi @dynamitechetan 

We are currently in the process of looking into some new development setups.
In the mean time, could you please adjust your `packages/extension/.env` file to the following:

```
NEXT_PUBLIC_API_URL=http://localhost:4000
#NEXT_PUBLIC_API_URL=https://api.daily.dev
NEXT_PUBLIC_SUBS_URL=ws://localhost:5000/graphql
NEXT_PUBLIC_DOMAIN=localhost
NEXT_PUBLIC_GA=UA-109059578-2
NEXT_PUBLIC_AMPLITUDE=46a18c8e538f37fbb74150e458b5c574
NEXT_PUBLIC_FLAGSMITH=LZp89Rk56sytKH9AeHyCtF

NEXT_PUBLIC_WEBAPP_URL=http://localhost:5002/
```

**Comment by yashdev9274** [comment]
@rebelchris may I work on it.
Do I have to replace the whole links?

**Comment by yashdev9274** [comment]
#1358 PR. Updated the API URL mentioned in issue #1341
