### ISSUE TITLE
tailwind concatenating classes

### ISSUE THREAD

**Issue by sshanzel** [dailydotdev/apps#1386]
While reviewing [this PR](https://github.com/dailydotdev/apps/pull/1385/files) I have noticed an issue in the `ModalFooter` component, more of a common pitfall with using tailwindcss.

Concatenation of string to produce a specific class is not encouraged. I can't find the particular doc page from them but the concern with using this process is the classes will get tree-shaken.  Hence, it might not work in the production build.

https://github.com/dailydotdev/apps/blob/8d6ee1d856d289e82cb9082c0a6deefec623c6ee/packages/shared/src/components/modals/common/ModalFooter.tsx#L24

cc @rebelchris @el 

It was way back. Not sure if that has changed now though.

**Comment by rebelchris** [comment]
Oh good find Lee, this is indeed a concern as we should only opt to use the fully qualified names, totally missed this one.

**Comment by sshanzel** [comment]
After digging through the tailwindcss docs, I finally found the relevant page. It seems to be still the case as discussed here:

https://tailwindcss.com/docs/content-configuration#dynamic-class-names

**Comment by rebelchris** [comment]
I'll add it to our board and pick it up in Eliz's absence.

**Comment by sshanzel** [comment]
Oh, totally forgot about it. Sorry for tagging! 🙏

**Comment by sshanzel** [comment]
We should probably include the link as well in our onboarding guide around getting to know more of our code base as it is really to fall into this trap if you haven't used tailwindcss in the past.

**Comment by el** [comment]
@sshanzel Amazing find, I wasn't aware of this recommendation but it makes total sense.
