### ISSUE TITLE
issue in gitpod setup 

### ISSUE THREAD

**Issue by Noothan-am** [dailydotdev/apps#2163]
when i tried to setup project using gitpod it throws error
![image](https://github.com/dailydotdev/apps/assets/100135382/a373f10e-66eb-4add-bf92-4af2d7d0779e)

**Comment by rebelchris** [comment]
Hi @Noothan-am thanks for reporting, this is indeed a issue we recently introduced by accident.
We'll work on fixing this as soon as possible 🙏

**Comment by Noothan-am** [comment]
hey @rebelchris, gitpod is the only way to clone this project?

**Comment by rebelchris** [comment]
Hi @Noothan-am Gitpod and a local env, but that takes more effort.

I just fixed the Gitpod though so please try that again 🙏
