### ISSUE TITLE
Lerna Bootstrap now removed in V7

### ISSUE THREAD

**Issue by AlexxMart** [dailydotdev/apps#2249]
Hello,

I'm trying to run the daily repo following the steps in the README.md but the step #1 in the "[Setting Up Daily Apps](https://github.com/dailydotdev/daily#-setting-up-daily-apps)" section is throwing an error since `lerna bootstrap` has been removed in the latest lerna version

```sh
ERR! bootstrap The "bootstrap" command was removed by default in v7, and is no longer maintained.
ERR! bootstrap Learn more about this change at https://lerna.js.org/docs/legacy-package-management
```

The solution to this would be to add the workspace path directly to the `package.json` in root  just like so and then run `pnpm install`

```json
{
  "name": "daily-apps",
  "private": true,
  "workspaces": [
    "packages/*"
  ],
  "dependencies": {
    "@babel/runtime": "^7.17.9",
    "postcss-rem-to-responsive-pixel": "^5.1.1"
  }
}
```

I created this as an issue instead of making a PR with the changes to the readme and the json because you guys would know best if that's the best approach or how to phrase it in the doc.

**Comment by AlexxMart** [comment]
Lerna's doc with this approach as the recommended solution: https://lerna.js.org/docs/legacy-package-management

**Comment by sshanzel** [comment]
Hi @AlexxMart, thank you for taking the time to write a fix relating to the setup. Unfortunately, our docs haven't been updated and we are not using Lerna anymore. For those who are looking to contribute we highly encourage people to use our [GitPod setup](https://gitpod.io/#https://github.com/dailydotdev/apps/).
