### ISSUE TITLE
Scroll bar improvement?

### ISSUE THREAD

**Issue by RajvirSingh1313** [dailydotdev/apps#450]
I think the scroll bar is a bit chunky 😕 so it should be clean like this scroll bar:- ` 
::-webkit-scrollbar {
    width: 7px;
}
::-webkit-scrollbar-thumb {
    background: rgb(179, 179, 179);
    border-radius: 10px;
}
::-webkit-scrollbar-track {
    background: #494949;
    padding: 10px;
}`
I don't know typescript or web dev enough to make a pull request with it and I even know that scroll bar is not a big deal 😅 but I think that would be helpful 😊 so I hope you will like it. And you can change the color though I just wrote it at the spot so the colors are random 😅.

**Comment by idoshamun** [comment]
Hey @RajvirSingh1313,

Thanks for the suggestion.
Could you please describe to me what scrollbar you refer to?
We have two types, the default one is the scroll of the window. The second type is a scrollbar of specific elements and this one has a custom design.

**Comment by RajvirSingh1313** [comment]
Hey @idoshamun,
Window one which is the simple scroll bar on the browser, The code I mentioned will just change the appearance of the scroll bar specifically for the daily.dev I hope you can understand.

**Comment by Nazeeh21** [comment]
> I think the scroll bar is a bit chunky 😕 so it should be clean like this scroll bar:- ` ::-webkit-scrollbar { width: 7px; } ::-webkit-scrollbar-thumb { background: rgb(179, 179, 179); border-radius: 10px; } ::-webkit-scrollbar-track { background: #494949; padding: 10px; }`
> I don't know typescript or web dev enough to make a pull request with it and I even know that scroll bar is not a big deal 😅 but I think that would be helpful 😊 so I hope you will like it. And you can change the color though I just wrote it at the spot so the colors are random 😅.

I would be interested in trying this out and solving this.

**Comment by Nazeeh21** [comment]
I am interested in solving this.

**Comment by idoshamun** [comment]
@Nazeeh21 we already have a custom scrollbar for the sidebar that you can find here:
https://github.com/dailydotdev/apps/blob/master/packages/shared/src/styles/utilities.css#L19

What we can do is to apply it globally instead of scoping it to a specific class.
The right place for the new global style will be in this file:
https://github.com/dailydotdev/apps/blob/master/packages/shared/src/styles/base.css

You can give it a try and let's see how it looks. 🤭

**Comment by Nazeeh21** [comment]
Yeah sure. I'll try to solve it.

**Comment by Nazeeh21** [comment]
I  am following the guide from [given here](https://github.com/dailydotdev/daily#%EF%B8%8F-setting-up-daily-services) to run dailydotdev locally. 

While running the command mentioned in **step 2**, I am getting the error as shown below:
![image](https://user-images.githubusercontent.com/56908732/123279261-53b7e900-d525-11eb-8665-798d20834cb6.png)

While running the command mentioned in **step 3**, I am getting the error as shown below:

![image](https://user-images.githubusercontent.com/56908732/123279452-7f3ad380-d525-11eb-928a-8e4813793f0f.png)

After this long error, I am getting "no issues found" as shown below:
![image](https://user-images.githubusercontent.com/56908732/123279763-c9bc5000-d525-11eb-9956-af548fd9d287.png)


Please help me solve these errors.

**Comment by idoshamun** [comment]
What's the node and npm version you use?
It should be node v14.16 and npm v6

**Comment by Nazeeh21** [comment]
Yes my npm version is 6

**Comment by idoshamun** [comment]
What about node?

**Comment by Nazeeh21** [comment]
My node version is 10.
I will try running the commands again after upgrading it to 14. ;-D

**Comment by Nazeeh21** [comment]
I upgraded to node v-14.
I am not encountering the error in the extension folder now

![Screenshot from 2021-06-24 20-51-23](https://user-images.githubusercontent.com/56908732/123289501-27ed3100-d52e-11eb-92ed-ba57ff3e5641.png)


But I am still encountering in the /webapp folder on running command "npm run dev"

![Screenshot from 2021-06-24 20-51-18](https://user-images.githubusercontent.com/56908732/123289681-4bb07700-d52e-11eb-86df-360faf26ffbc.png).

I am also sharing the screenshot of running the command "docker-compose pull && docker-compose up" from **step 2** from the guide

![Screenshot from 2021-06-24 20-54-37](https://user-images.githubusercontent.com/56908732/123290298-c5486500-d52e-11eb-8c36-dd6eae126852.png)

**Comment by idoshamun** [comment]
That's weird. Please check now that your npm version is v6

**Comment by Nazeeh21** [comment]
Yes it is v6

![Screenshot from 2021-06-24 21-03-42](https://user-images.githubusercontent.com/56908732/123291395-b0b89c80-d52f-11eb-84fd-729126495222.png)

**Comment by idoshamun** [comment]
@Nazeeh21 I will have to check it but in the meantime, you can evaluate your changes in the extension

**Comment by idoshamun** [comment]
Oh, maybe you have to run `npx lerna bootstrap` again. Try it and let me know :)

**Comment by Nazeeh21** [comment]
I think I have resolved the error, sharing the screenshots of all three running scripts.

screenshot from "docker-compose pull && docker-compose up"  script.
![Screenshot from 2021-06-24 21-40-20](https://user-images.githubusercontent.com/56908732/123297529-4571c900-d535-11eb-8093-af2777324a5c.png)


screenshot from "npm run dev" in /packages/webapps folder.
![image](https://user-images.githubusercontent.com/56908732/123297628-5b7f8980-d535-11eb-87df-de82d75863fc.png)

screenshot from "npm run dev: chrome" in /packages/extensions folder.
![Screenshot from 2021-06-24 21-40-32](https://user-images.githubusercontent.com/56908732/123297704-7225e080-d535-11eb-9c41-72bedc1e9f17.png)

I think I have resolved the error. :-)

**Comment by idoshamun** [comment]
Yap! Way to go 🤩

**Comment by Nazeeh21** [comment]
I think I have solved it.
![Screenshot from 2021-06-24 21-56-22](https://user-images.githubusercontent.com/56908732/123299348-0f354900-d537-11eb-981d-6a3af322ba04.png)

Please guide me if anything wrong.

**Comment by idoshamun** [comment]
Please submit a PR so I will be able to check it out 😊

**Comment by RajvirSingh1313** [comment]
Hey Ido, I know this talk is kinda gonna be out of context, But I want you
to make a blog about how to create complex react or vue chrome extensions.
I am looking for project to implement but I can't find good source so if
you can write a blog about it, then it would be great

**Comment by idoshamun** [comment]
Hey @RajvirSingh1313,

I will do my best to address your request. Please note that I'm super busy lately so it might take a while.

**Comment by RajvirSingh1313** [comment]
Thanks Alot

**Comment by idoshamun** [comment]
Thank you @Nazeeh21 for helping us out and contributing this fix 🙏

**Comment by Nazeeh21** [comment]
It's my pleasure to contribute to this project.
