### ISSUE TITLE
Generate dev card page isn't responsive 

### ISSUE THREAD

**Issue by devgossips** [dailydotdev/apps#670]
![Screenshot_2021-11-07-17-41-15-990_com android chrome](https://user-images.githubusercontent.com/70798495/140644397-057e21a8-fb33-4a0d-9cde-28d7f399d2e7.jpg)
DOWNLOAD and COPY LINK button overlap each other

**Comment by idoshamun** [comment]
Hi @devgossips,

Thanks a lot for reporting this. We will forward it to our design team and release a fix.
I'll keep you posted.

**Comment by idoshamun** [comment]
@devgossips it should be fixed by now. Please confirm :)
