### ISSUE TITLE
Npm install error

### ISSUE THREAD

**Issue by avneesh0612** [dailydotdev/apps#688]
I keep getting this error whenever I try to install a dependency, run the app or do anything-
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@dailydotdev%2fshared - Not found
npm ERR! 404 
npm ERR! 404  '@dailydotdev/shared@*' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'webapp'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git URL.
```

**Comment by sshanzel** [comment]
Hi @avneesh0612, thank you for reaching out. We love to welcome you in running daily locally!

With regards to the issue, have you tried running `npx lerna bootstrap`? It should take care of installing the necessary packages.

**Comment by avneesh0612** [comment]
Hey, I did run `lerna bootstrap`

**Comment by sshanzel** [comment]
Wow, you are very quick! Once done running the command, you should be able start running your desired package.

For the `webapp`: `npm run dev`

For the `extension`: `npm run dev:<browser>`. Kindly replace the `<browser>` with either `chrome` or `firefox`

**Comment by avneesh0612** [comment]
haha, I tried again after deleting and re install the packages and the whole repo. Seems like it worked :D

**Comment by avneesh0612** [comment]
Thanks for helping out :)

**Comment by avneesh0612** [comment]
I am getting another error in webapp tho-

```
error - Error: connect ECONNREFUSED 127.0.0.1:4000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 4000
}
```

**Comment by sshanzel** [comment]
Awesome! Thank you so much for the clear details! You are one step away from running it end to end!

Based on the logs you have mentioned, the only thing missing now should be the services.

Since you have the repo already pulled up, you can follow these [easy steps](https://github.com/dailydotdev/daily#-step-0) to have it up and running or you can watch a full walkthrough by our team in the video link below:

https://www.youtube.com/watch?v=sNUpOJaL_B8

**Comment by avneesh0612** [comment]
Okay thanks :D

**Comment by sshanzel** [comment]
Great! Please don't hesitate to reach out whenever you need any help on anything to set up your local environment. I would be very glad to help. We wish you good luck on your Daily journey!

**Comment by avneesh0612** [comment]
Awesome, thanks!
