### ISSUE TITLE
Feed error for certain tags

### ISSUE THREAD

**Issue by jshuadvd** [dailydotdev/apps#838]
Hi there, I am experiencing an issue with the feed returning no posts for the `#blockchain` tag. It has been like this for about 4 days now. Please let me know if you need further information!

**Fingerprint Data**
```
macOS Big Sur 11.6
Chrome 97.0.4692.71
```

**Feed**
<img width="2042" alt="Screen Shot 2022-01-19 at 11 55 14 AM" src="https://user-images.githubusercontent.com/7577457/150204103-bc1a3ed8-3939-4e45-8a0d-c22e4b96397b.png">

**Console Errors**
<img width="2048" alt="Screen Shot 2022-01-19 at 11 48 06 AM" src="https://user-images.githubusercontent.com/7577457/150204239-03eb46b5-178d-4a9d-aea3-81bf2075d25d.png">

<img width="2048" alt="Screen Shot 2022-01-19 at 11 57 38 AM" src="https://user-images.githubusercontent.com/7577457/150204428-cc310c43-f470-4371-b962-47445ab49a14.png">

**Comment by idoshamun** [comment]
I just deployed a fix that should address this issue. Can you make sure you're running 3.13.0 and if so please confirm that the issues persists?

**Comment by jshuadvd** [comment]
@idoshamun this is still not corrected for me. Similarly, I am not seeing this in either of the production web app or extension.

**Comment by idoshamun** [comment]
@jshuadvd sorry for the late response, can you share your username so I can check our logs and data for a lead?

**Comment by jshuadvd** [comment]
@idoshamun no worries :) Yes, I have authorized via github, so the username is the same. `jshuadvd`

**Comment by idoshamun** [comment]
@jshuadvd Looking at your feed's data I see you have followed blockchain only and blocked many sources. Unfortunately, we don't have so much content about blockchain at this point so there's not a lot of inventory to show you. You also probably saw some of the older content we have already. You might want to consider following crypto and web3 if this makes sense or even other tags

**Comment by jshuadvd** [comment]
@idoshamun So the strange thing is that I was only following #blockchain before reporting this issue and I had an abundance of posts in my feed. All blockchain related mind you. So did something happen with the way that tags are associated with content? Similarly, I haven't blocked any other sources. I am only following the tag #blockchain tag. Thanks for all of your help.

**Comment by idoshamun** [comment]
Can you follow this guide and check if you blocked any source?
https://docs.daily.dev/docs/settingyourfeed/blocking-tags-sources#how-to-unblock-tags-and-sources

Last time I checked you had several sources blocked.

**Comment by jshuadvd** [comment]
Sure. Here are my results. BTW I have never blocked anything. It has always just been the #blockchian tag that I enabled in my feed. Everything was fine until the new update.

<img width="2048" alt="Screen Shot 2022-02-05 at 12 47 12 PM" src="https://user-images.githubusercontent.com/7577457/152658449-7b01ea7e-1289-42a4-a613-1f158ae3435e.png">

**Comment by idoshamun** [comment]
Thanks for sharing! I'll look into it :)

**Comment by jshuadvd** [comment]
Amazing! Yes! This is fixed now! Thank you! Will this continue to work as is, or is it a feature being released? Similarly, could you point me to where the code is so that I can have a look?

**Comment by idoshamun** [comment]
This is a beta feature so it might change occasionally and have some quirks but overall it should be fine.
Our feed service is currently closed source, so can't really show you anything in this regard.

**Comment by jshuadvd** [comment]
Hi @idoshamun This is happening again! I went to view Popular and Most Upvoted and as soon as I went back to my feed, there was only 1 post.

**Comment by idoshamun** [comment]
I recently introduced a new change to the algorithm, this is probably why you experience it again.
Before this change, whenever you opened the feed did you see the same articles over and over again?

**Comment by jshuadvd** [comment]
Ahh, I see! For the last few days before the issue presented itself, yes I was.

**Comment by idoshamun** [comment]
Unfortunately, we don't have many blockchain publications on daily.dev. This is kind of an edge case to our algorithm. I suggest using the sort by date feature to solve this issue.
Check it here:
https://docs.daily.dev/docs/key-features/default-feeds#sort-by-date-prev-recent-feed

Please let me know if it solves your issue
