### ISSUE TITLE
Localhost on MostVisited Sites

### ISSUE THREAD

**Issue by jromerooo2** [dailydotdev/apps#839]
Hey!,

I've noticed that localhost appears on my most visited sites, I don't know if this is meant to be, but I just wanted to report it.
I tried to open a PR but I wasn't able to, since I didn't manage to get the apps running locally. I got: 

`npm ERR! 404 Not Found - GET https://registry.npmjs.org/@dailydotdev%2Feslint-plugin-daily-dev-eslint-rules - Not found
npm ERR! 404 
npm ERR! 404  '@dailydotdev/eslint-plugin-daily-dev-eslint-rules@*' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
` 

and even tried to use npx lerna bootstrap as suggested in this thread : https://githubhelp.com/dailydotdev/apps/issues/688

**Comment by idoshamun** [comment]
Hi @jromerooo2,

We don't control the most visited sites, we receive it via the browser's API. So there's nothing really that we can do.
But we do plan on providing an option to customize this list.
