### ISSUE TITLE
email already used error while updating timezone

### ISSUE THREAD

**Issue by keshavashiya** [dailydotdev/apps#910]
Hi team,

getting email already used error while updating time zone.

```
{
    "code": 1,
    "message": "email already exists",
    "field": "email",
    "reason": "email already exists"
}
```

<img width="478" alt="Screenshot 2022-02-27 at 11 43 08 PM" src="https://user-images.githubusercontent.com/20239068/155894480-bcf129c7-3b0b-41d8-840d-e68dd286003a.png">

**Comment by idoshamun** [comment]
Hi @keshavashiya,

Please send us an email to support at daily.dev. We will fix this issue for you :)

**Comment by Abhijeetmishr** [comment]
Hi @idoshamun,
I am interested in contributing to this project.
Any suggestions to where I should look out for issues to fix.

Regards,
Abhijeet

**Comment by idoshamun** [comment]
Hi @Abhijeetmishr,

The issue is closed. Thanks for your support 🙏

**Comment by Abhijeetmishr** [comment]
Hi @idoshamun,
I wanted to contribute where should I start?

Thanks & Regards

**Comment by idoshamun** [comment]
@sshanzel will check if we have any open issues for contribution and will update you :)

**Comment by Abhijeetmishr** [comment]
> @sshanzel will check if we have any open issues for contribution and will update you :)

I appreciate this.
Thank you.

**Comment by Abhijeetmishr** [comment]
> Hi @Abhijeetmishr thank you for your patience. We have an existing issue with list view mode, if you are up to the challenge, just let me know. The description of the issue is explained here [dailydotdev/daily#828](https://github.com/dailydotdev/daily/issues/828).

Hey @sshanzel thank you for letting me know.
Yes I am excited for this.

Thanks

**Comment by Abhijeetmishr** [comment]
Hey @sshanzel where can I find the documentation for setting up project locally ?
